#THIS CONFIG FILE IS FOR COVID-19 KNOWLEDGE GRAPH AND DRUG REPURPOSING KNOWLEDGE GRAPH USE CASE
#WE USE THE DRKG AND COVID-19-KG AS THE INPUT DATASETS

#THERE ARE 7 MAIN LAYERS
#LAYER 1 - DDI DATA FROM DRKG
#LAYER 2 - GENE-GENE FROM DRKG
#LAYER 3 - PATHWAY-PHENOTYPE FROM COVID-19 KG
#LAYER 4 - TRANSCRIPT-TRANSCRIPT FROM DISEASE-STATE OMICS-SPECIFIC GRAPH
#LAYER 5 - PROTEIN-PROTEIN FROM DISEASE-STATE OMICS-SPECIFIC GRAPH
#LAYER 6 - LIPID-LIPID FROM DISEASE-STATE OMICS-SPECIFIC GRAPH
#LAYER 7 - METABOLOMICS-METABOLOMICS FROM DISEASE-STATE OMICS-SPECIFIC GRAPH


#THERE ARE  SIX MAIN BIPARTIE GRAPHS
#BIPARTITE 1 - GENE-COMPOUND FROM DKRG
#BIPARTITE 2 - GENE-CHEMICAL FROM COVID-19 KG
#BIPARTITE 3 - PATHWAY-GENE FROM COVID-19 KG
#BIPARTITE 4 - PHENOTYPE-GENE FROM COVID-19 KG
#BIPARTITE 5 - PHENOTYPE-CHEMICAL FROM COVID-19 KG
#BIPARTITE 6 - VIRUS-HOST FROM COVID-19 KG  
#BIPARTITE 7 - 




#hypothesis approach using IL6 and IL6R as seeds
#seed: seeds_hypo_driven_KG.txt
#seeds_hypo_driven_KG_and_Ritonavir.txt

#data-driven approach using top-ranked features based on integrated centrality score as seed
seed: seeds_data_driven.txt

r: 0.7
# self_loops: Are self-loops allowed? 1 yes, 0 not
self_loops: 1
# eta: Restart probability for each multiplex. Must sum up to one.
eta: [1/6, 1/6, 1/6, 1/6, 1/6, 1/6]
#4. Inter multiplex Networks Jump Probability (lambda)
lamb:
    - [1/6, 1/6, 1/6, 1/6, 1/6, 1/6]
    - [1/6, 1/6, 1/6, 1/6, 1/6, 1/6]
    - [1/6, 1/6, 1/6, 1/6, 1/6, 1/6]
    - [1/6, 1/6, 1/6, 1/6, 1/6, 1/6]
    - [1/6, 1/6, 1/6, 1/6, 1/6, 1/6]
    - [1/6, 1/6, 1/6, 1/6, 1/6, 1/6]

    #- [1]


multiplex:
    1:
        layers:
            - Networks/Proteomics-all_sig_mild_absolute_PCC_0.1.txt
#            - Networks/Transcriptomics-all_sig_severe_absolute_PCC.txt1
#            - Networks/Metabolomics-all_sig_severe_absolute_PCC.txt1

        delta: 0.5
        # Graph type: unweighted/weighted, undirected/directed
        #graph_type: [00, 00, 00]
        graph_type: [00]
        # Restart probabily 3. Layers Restart Probability (tau)
#        tau: [1/3, 1/3, 1/3]
        tau: [1]
    2:
        layers:
            - COVID_KG/Drug_repurposing_knowledge_Graph/files/Drug_repurposing_knowledge_Graph_Gene_Gene_map_uniq.txt
            - Networks/Transcriptomics-all_sig_mild_absolute_PCC_0.1_uniq_IL6.txt
            - COVID_KG/COVID_knowledge_Graph/files/virus_host_extracted_map3.txt
#            - Networks/Transcriptomics-all_sig_severe_absolute_PCC.txt1
#            - Networks/Transcriptomics-all_sig_severe_absolute_PCC.txt1
        delta: 0.5
        graph_type: [00, 00,00]
#        graph_type: [00]
        tau: [1/3, 1/3, 1/3]
#        tau: [1]

    3:
        layers:
            - Networks/Metabolomics-all_sig_mild_absolute_PCC_0.1.txt
 #           - Networks/Metabolomics-all_sig_severe_absolute_PCC.txt1
 #           - Networks/Metabolomics-all_sig_severe_absolute_PCC.txt1
        delta: 0.5
        #graph_type: [00, 00, 00]
        graph_type: [00]
#        tau: [1/3, 1/3, 1/3]
        tau: [1]

    4:
        layers:
            - Networks/Lipidomics-all_sig_mild_absolute_PCC_0.1.txt
 #           - Networks/Metabolomics-all_sig_severe_absolute_PCC.txt1
 #           - Networks/Metabolomics-all_sig_severe_absolute_PCC.txt1
        delta: 0.5
        #graph_type: [00, 00, 00]
        graph_type: [00]
#        tau: [1/3, 1/3, 1/3]
        tau: [1]


    5:
        layers:
            #- COVID_KG/Drug_repurposing_knowledge_Graph/files/Drug_repurposing_knowledge_Graph_DDI_map_uniq_KO_Dexamethasone.txt
            #- COVID_KG/Drug_repurposing_knowledge_Graph/files/Drug_repurposing_knowledge_Graph_DDI_map_uniq_KO_Tocilizumab.txt
            #- COVID_KG/Drug_repurposing_knowledge_Graph/files/Drug_repurposing_knowledge_Graph_DDI_map_uniq_KO_Sarilumab.txt
            #- COVID_KG/Drug_repurposing_knowledge_Graph/files/Drug_repurposing_knowledge_Graph_DDI_map_uniq_KO_Dex_Toci_Sari.txt
            #- COVID_KG/Drug_repurposing_knowledge_Graph/files/Drug_repurposing_knowledge_Graph_DDI_map_uniq_KO_Glu_Cri_Curcu.txt
            #- COVID_KG/Drug_repurposing_knowledge_Graph/files/Drug_repurposing_knowledge_Graph_DDI_map_uniq_KO_Glutathione.txt
            #- COVID_KG/Drug_repurposing_knowledge_Graph/files/Drug_repurposing_knowledge_Graph_DDI_map_uniq_KO_Crizotinib.txt
            - COVID_KG/Drug_repurposing_knowledge_Graph/files/Drug_repurposing_knowledge_Graph_DDI_map_uniq_KO_Curcumin.txt
        delta: 0.5
        graph_type: [00]
        tau: [1]

#    2:
#        layers:
#            - COVID_KG/Drug_repurposing_knowledge_Graph/files/Drug_repurposing_knowledge_Graph_Gene_Gene_map_uniq.txt
#            - Networks/Lipidomics-all_sig_mild_absolute_PCC_0.1.txt
#            - Networks/Metabolomics-all_sig_mild_absolute_PCC_0.1.txt
#        delta: 0.5
#        graph_type: [00,00,00]
#        tau: [1/3,1/3,1/3]

    6:
        layers:
            - COVID_KG/COVID_knowledge_Graph/files/phenotype_pathway_interaction_map3.txt

        delta: 0.5
        graph_type: [00]
        tau: [1]



bipartite:
    bipartite/Overmyer-Su-cross-layer_including_unknown_protein-metabolite.txt12: {source: 2, 'target': 3}
    bipartite/Overmyer-Su-cross-layer_including_unknown_lipid-protein.txt1: {source: 4, 'target': 2}




    #COVID_KG/Drug_repurposing_knowledge_Graph/files/Drug_repurposing_knowledge_Graph_Gene_Compound_map_uniq_KO_Dexamethasone.txt: {source: 2, 'target': 5}
    #COVID_KG/Drug_repurposing_knowledge_Graph/files/Drug_repurposing_knowledge_Graph_Gene_Compound_map_uniq_KO_Tocilizumab.txt: {source: 2, 'target': 5}
    #COVID_KG/Drug_repurposing_knowledge_Graph/files/Drug_repurposing_knowledge_Graph_Gene_Compound_map_uniq_KO_Sarilumab.txt: {source: 2, 'target': 5}
    #COVID_KG/Drug_repurposing_knowledge_Graph/files/Drug_repurposing_knowledge_Graph_Gene_Compound_map_uniq_KO_Dex_Toci_Sari.txt: {source: 2, 'target': 5}
    #COVID_KG/Drug_repurposing_knowledge_Graph/files/Drug_repurposing_knowledge_Graph_Gene_Compound_map_uniq_KO_Glu_Cri_Curcu.txt: {source: 2, 'target': 5}
    #COVID_KG/Drug_repurposing_knowledge_Graph/files/Drug_repurposing_knowledge_Graph_Gene_Compound_map_uniq_KO_Glutathione.txt: {source: 2, 'target': 5}
    #COVID_KG/Drug_repurposing_knowledge_Graph/files/Drug_repurposing_knowledge_Graph_Gene_Compound_map_uniq_KO_Crizotinib.txt: {source: 2, 'target': 5}
    COVID_KG/Drug_repurposing_knowledge_Graph/files/Drug_repurposing_knowledge_Graph_Gene_Compound_map_uniq_KO_Curcumin.txt: {source: 2, 'target': 5}
    #COVID_KG/COVID_knowledge_Graph/files/COVID-19_Genes_Interaction_with_chemicals-CTD_map4.txt: {source: 2, 'target': 5}
    COVID_KG/COVID_knowledge_Graph/files/Pathways_Interaction_with_COVID-19_Genes_map3.txt: {source: 6, 'target': 2}
    COVID_KG/COVID_knowledge_Graph/files/Phenotypes_Interactions_with_COVID-19_Genes_map3.txt: {source: 6, 'target': 2}
    COVID_KG/COVID_knowledge_Graph/files/Phenotypes_Interactions_with_COVID-19_chemicals_map3.txt: {source: 6, 'target': 5}
   # COVID_KG/COVID_knowledge_Graph/files/virus_host_extracted_map3.txt: {source: 2, 'target': 2}
   # bipartite/bigraph.txt: {source: 2, 'target': 2}

    #bipartite/Overmyer-Su-cross-layer_including_unknown_protein-transcript.txt1: {source: 5, 'target': 4}
 #   bipartite/Overmyer-Su-cross-layer_including_unknown_protein-metabolite.txt12: {source: 3, 'target': 6}
    #bipartite/Overmyer-Su-cross-layer_including_unknown_lipid-protein.txt1: {source: 6, 'target': 5}
  #  COVID_KG/Drug_repurposing_knowledge_Graph/files/Drug_repurposing_knowledge_Graph_Gene_Compound_map_uniq.txt: {source: 4, 'target': 1}
    #COVID_KG/COVID_knowledge_Graph/files/Phenotypes_Interactions_with_COVID-19_Genes_map3.txt: {source: 2, 'target': 4}
